### ISSUE TITLE
wrong game name hardcoded

### ISSUE THREAD

**Issue by IbrahimElk** [ML-KULeuven/ml-project-2022-2023#1]
In the file `dotsandboxes_agent/dotsandboxes_agent.py` the hardcoded name of the game under the function `test_api_calls`
```
    dotsandboxes_game_string = (
        "dotsandboxes(num_rows=5,num_cols=5)")
```
It probably should be 

```
    dotsandboxes_game_string = (
        "dots_and_boxes(num_rows=5,num_cols=5)")
```

This was also the case on the departments computer under the baseline folder. 
I could not create a pull request to change this, so this is why i submitted this issue. 
I'm not so familiar with creating issues, please correct me or how i should correctly add an issue if I've done something wrong.

**Comment by probberechts** [comment]
Thanks for pointing this out!
